project:
  type: website
  output-dir: docs

website:
  title: "2026 ESS 523c"
  navbar:
    left:
      - href: /2026-ESS-523c/index.html
        text: Home
      - href: /2026-ESS-523c/lab-01.html
        text: Lab 1
      - href: /2026-ESS-523c/lab-02.html
        text: Lab 2
      - href: /2026-ESS-523c/lab-03.html
        text: Lab 3
