<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lab 6: Timeseries Data – 2026 ESS 523c</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ff63373b1067ca6f91cf1456aa1f00a2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.11.0/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="site_libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">2026 ESS 523c</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./lab-01.html"> 
<span class="menu-text">Lab 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./lab-02.html"> 
<span class="menu-text">Lab 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./lab-03.html"> 
<span class="menu-text">Lab 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./lab-04.html"> 
<span class="menu-text">Lab 4</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./lab-05.html"> 
<span class="menu-text">Lab 5</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./lab-06.html" aria-current="page"> 
<span class="menu-text">Lab 6</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#getting-the-data" id="toc-getting-the-data" class="nav-link" data-scroll-target="#getting-the-data">Getting the Data</a>
  <ul class="collapse">
  <li><a href="#streamflow" id="toc-streamflow" class="nav-link" data-scroll-target="#streamflow">Streamflow</a></li>
  <li><a href="#historic-climate-gridmet" id="toc-historic-climate-gridmet" class="nav-link" data-scroll-target="#historic-climate-gridmet">Historic Climate (GridMET)</a></li>
  <li><a href="#future-climate-maca" id="toc-future-climate-maca" class="nav-link" data-scroll-target="#future-climate-maca">Future Climate (MACA)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#your-turn" id="toc-your-turn" class="nav-link" data-scroll-target="#your-turn">Your Turn</a>
  <ul class="collapse">
  <li><a href="#convert-to-tsibble" id="toc-convert-to-tsibble" class="nav-link" data-scroll-target="#convert-to-tsibble">1. Convert to tsibble</a></li>
  <li><a href="#plot-the-time-series" id="toc-plot-the-time-series" class="nav-link" data-scroll-target="#plot-the-time-series">2. Plot the Time Series</a></li>
  <li><a href="#seasonal-diagnostics" id="toc-seasonal-diagnostics" class="nav-link" data-scroll-target="#seasonal-diagnostics">3. Seasonal Diagnostics</a></li>
  <li><a href="#stationarity-and-autocorrelation" id="toc-stationarity-and-autocorrelation" class="nav-link" data-scroll-target="#stationarity-and-autocorrelation">4. Stationarity and Autocorrelation</a></li>
  <li><a href="#decomposition" id="toc-decomposition" class="nav-link" data-scroll-target="#decomposition">5. Decomposition</a></li>
  <li><a href="#modeltime-prediction" id="toc-modeltime-prediction" class="nav-link" data-scroll-target="#modeltime-prediction">Modeltime Prediction</a>
  <ul class="collapse">
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data Preparation</a></li>
  <li><a href="#train-test-split" id="toc-train-test-split" class="nav-link" data-scroll-target="#train-test-split">Train / Test Split</a></li>
  <li><a href="#model-definition" id="toc-model-definition" class="nav-link" data-scroll-target="#model-definition">Model Definition</a></li>
  <li><a href="#model-fitting" id="toc-model-fitting" class="nav-link" data-scroll-target="#model-fitting">Model Fitting</a></li>
  <li><a href="#calibration-and-accuracy" id="toc-calibration-and-accuracy" class="nav-link" data-scroll-target="#calibration-and-accuracy">Calibration and Accuracy</a></li>
  <li><a href="#test-set-forecast" id="toc-test-set-forecast" class="nav-link" data-scroll-target="#test-set-forecast">Test Set Forecast</a></li>
  <li><a href="#refit-to-full-dataset" id="toc-refit-to-full-dataset" class="nav-link" data-scroll-target="#refit-to-full-dataset">Refit to Full Dataset</a></li>
  <li><a href="#forecast-into-the-future-20242033" id="toc-forecast-into-the-future-20242033" class="nav-link" data-scroll-target="#forecast-into-the-future-20242033">Forecast into the Future (2024–2033)</a></li>
  </ul></li>
  <li><a href="#wrap-up" id="toc-wrap-up" class="nav-link" data-scroll-target="#wrap-up">Wrap-up</a></li>
  <li><a href="#going-further-optional-add-an-upstream-regressor" id="toc-going-further-optional-add-an-upstream-regressor" class="nav-link" data-scroll-target="#going-further-optional-add-an-upstream-regressor">Going Further (Optional): Add an Upstream Regressor</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 6: Timeseries Data</h1>
<p class="subtitle lead">Using Modeltime to predict future streamflow on the Cache la Poudre River</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In this lab you will download streamflow data from the Cache la Poudre River (USGS site 06752260) and analyze it using the time series methods introduced in lecture. You will then use <code>modeltime</code> to predict future streamflow using both the time structure of the series and exogenous climate predictors.</p>
<p>This mirrors the Lees Ferry forecasting example from lecture — same <code>dataRetrieval</code> pipeline, same <code>modeltime</code> workflow, but now applied to a river you can see from campus. Like Lees Ferry, the Poudre is an operational water-supply system: Fort Collins, Loveland, and Greeley all depend on it, and the flows you forecast here directly inform how water managers plan deliveries.</p>
<section id="getting-the-data" class="level2">
<h2 class="anchored" data-anchor-id="getting-the-data">Getting the Data</h2>
<section id="streamflow" class="level3">
<h3 class="anchored" data-anchor-id="streamflow">Streamflow</h3>
<p>Download daily streamflow for the Poudre at Mouth (USGS 06752260) and aggregate to monthly means. This is the same <code>readNWISdv()</code> + <code>renameNWISColumns()</code> pipeline from Lab 1 — the only addition is <code>yearmonth()</code> from <code>tsibble</code> to create a monthly time index.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>poudre_flow <span class="ot">&lt;-</span> <span class="fu">readNWISdv</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">siteNumber =</span> <span class="st">"06752260"</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">parameterCd =</span> <span class="st">"00060"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">startDate   =</span> <span class="st">"2013-01-01"</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">endDate     =</span> <span class="st">"2023-12-31"</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">renameNWISColumns</span>() <span class="sc">|&gt;</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">yearmonth</span>(Date)) <span class="sc">|&gt;</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Date) <span class="sc">|&gt;</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Flow =</span> <span class="fu">mean</span>(Flow))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="historic-climate-gridmet" class="level3">
<h3 class="anchored" data-anchor-id="historic-climate-gridmet">Historic Climate (GridMET)</h3>
<p>We will use <code>climateR::getTerraClim()</code> to download monthly climate data for the Poudre basin (max temperature, precipitation, solar radiation). The <code>exactextractr</code> package spatially averages each raster layer over the basin polygon.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>basin <span class="ot">&lt;-</span> <span class="fu">findNLDI</span>(<span class="at">nwis =</span> <span class="st">"06752260"</span>, <span class="at">find =</span> <span class="st">"basin"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>sdate <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2013-01-01"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>edate <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2023-12-31"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>gm <span class="ot">&lt;-</span> <span class="fu">getTerraClim</span>(</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">AOI       =</span> basin<span class="sc">$</span>basin,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">var       =</span> <span class="fu">c</span>(<span class="st">"tmax"</span>, <span class="st">"ppt"</span>, <span class="st">"srad"</span>),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">startDate =</span> sdate,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">endDate   =</span> edate</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unlist</span>() <span class="sc">|&gt;</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rast</span>() <span class="sc">|&gt;</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">exact_extract</span>(basin<span class="sc">$</span>basin, <span class="st">"mean"</span>, <span class="at">progress =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>historic <span class="ot">&lt;-</span> <span class="fu">mutate</span>(gm, <span class="at">id =</span> <span class="st">"gridmet"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>id) <span class="sc">|&gt;</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">name =</span> <span class="fu">sub</span>(<span class="st">"^mean</span><span class="sc">\\</span><span class="st">."</span>, <span class="st">""</span>, name)) <span class="sc">|&gt;</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">extract</span>(name, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"var"</span>, <span class="st">"index"</span>), <span class="st">"(.*)_([^_]+$)"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">index =</span> <span class="fu">as.integer</span>(index)) <span class="sc">|&gt;</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">yearmonth</span>(<span class="fu">seq.Date</span>(sdate, edate, <span class="at">by =</span> <span class="st">"month"</span>)[<span class="fu">as.numeric</span>(index)])) <span class="sc">|&gt;</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> Date, <span class="at">names_from =</span> var, <span class="at">values_from =</span> value) <span class="sc">|&gt;</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(poudre_flow, <span class="at">by =</span> <span class="st">"Date"</span>)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Validate: should have 132 rows (11 years × 12 months). If fewer, climate data</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="co"># is missing for some months and those flow months were silently dropped.</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="st">"Climate join dropped flow months — check GridMET download"</span> <span class="ot">=</span> <span class="fu">nrow</span>(historic) <span class="sc">==</span> <span class="dv">132</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="future-climate-maca" class="level3">
<h3 class="anchored" data-anchor-id="future-climate-maca">Future Climate (MACA)</h3>
<p>Any time exogenous predictors are used for forecasting, <strong>future values of those predictors must also be available</strong>. We use MACA — a statistically downscaled climate dataset developed by the same group as GridMET — to get projected temperature, precipitation, and solar radiation through 2033.</p>
<p>Two differences from GridMET: temperature is in Kelvin (subtract 273.15 for °C) and variable names differ slightly.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>sdate <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2024-01-01"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>edate <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2033-12-31"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>maca <span class="ot">&lt;-</span> <span class="fu">getMACA</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">AOI      =</span> basin<span class="sc">$</span>basin,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">var      =</span> <span class="fu">c</span>(<span class="st">"tasmax"</span>, <span class="st">"pr"</span>, <span class="st">"rsds"</span>),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">timeRes  =</span> <span class="st">"month"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">startDate =</span> sdate,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">endDate   =</span> edate</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unlist</span>() <span class="sc">|&gt;</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rast</span>() <span class="sc">|&gt;</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">exact_extract</span>(basin<span class="sc">$</span>basin, <span class="st">"mean"</span>, <span class="at">progress =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>future <span class="ot">&lt;-</span> <span class="fu">mutate</span>(maca, <span class="at">id =</span> <span class="st">"maca"</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>id) <span class="sc">|&gt;</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">name =</span> <span class="fu">sub</span>(<span class="st">"^mean</span><span class="sc">\\</span><span class="st">."</span>, <span class="st">""</span>, name)) <span class="sc">|&gt;</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">extract</span>(name, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"var"</span>, <span class="st">"index"</span>), <span class="st">"(.*)_([^_]+$)"</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">index =</span> <span class="fu">as.integer</span>(index)) <span class="sc">|&gt;</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">yearmonth</span>(<span class="fu">seq.Date</span>(sdate, edate, <span class="at">by =</span> <span class="st">"month"</span>)[<span class="fu">as.numeric</span>(index)])) <span class="sc">|&gt;</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> Date, <span class="at">names_from =</span> var, <span class="at">values_from =</span> value)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the 3 climate columns to match GridMET names (Date column stays first)</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="st">"Unexpected MACA column count"</span> <span class="ot">=</span> <span class="fu">ncol</span>(future) <span class="sc">==</span> <span class="dv">4</span>)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(future)[<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ppt"</span>, <span class="st">"srad"</span>, <span class="st">"tmax"</span>)  <span class="co"># order matches getMACA var request</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>future <span class="ot">&lt;-</span> <span class="fu">mutate</span>(future, <span class="at">tmax =</span> tmax <span class="sc">-</span> <span class="fl">273.15</span>)   <span class="co"># Kelvin → °C</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<hr>
</section>
</section>
</section>
<section id="your-turn" class="level1">
<h1>Your Turn</h1>
<section id="convert-to-tsibble" class="level2">
<h2 class="anchored" data-anchor-id="convert-to-tsibble">1. Convert to tsibble</h2>
<p>Convert <code>historic</code> to a <code>tsibble</code> object using <code>as_tsibble()</code>. A <code>tsibble</code> is a tidy time series data frame — it retains the date index and integrates with <code>feasts</code> functions for decomposition and visualization. Think of it as a tibble that knows it is ordered in time.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Using `Date` as index variable.</code></pre>
</div>
</div>
</section>
<section id="plot-the-time-series" class="level2">
<h2 class="anchored" data-anchor-id="plot-the-time-series">2. Plot the Time Series</h2>
<p>Use <code>ggplot</code> to plot monthly Flow over time. Use <code>plot_ly()</code> from <code>plotly</code> for an interactive version — this lets you zoom into specific years or hover over values.</p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-1b5409e37351b7258aa4" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-1b5409e37351b7258aa4">{"x":{"visdat":{"ec321eae11b1":["function () ","plotlyVisDat"]},"cur_data":"ec321eae11b1","attrs":{"ec321eae11b1":{"x":{},"y":{},"mode":"lines","line":{"color":"steelblue"},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Monthly Streamflow — Cache la Poudre at Mouth","xaxis":{"domain":[0,1],"automargin":true,"title":"Date"},"yaxis":{"domain":[0,1],"automargin":true,"title":"Flow (cfs)"},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["2013-01-01","2013-02-01","2013-03-01","2013-04-01","2013-05-01","2013-06-01","2013-07-01","2013-08-01","2013-09-01","2013-10-01","2013-11-01","2013-12-01","2014-01-01","2014-02-01","2014-03-01","2014-04-01","2014-05-01","2014-06-01","2014-07-01","2014-08-01","2014-09-01","2014-10-01","2014-11-01","2014-12-01","2015-01-01","2015-02-01","2015-03-01","2015-04-01","2015-05-01","2015-06-01","2015-07-01","2015-08-01","2015-09-01","2015-10-01","2015-11-01","2015-12-01","2016-01-01","2016-02-01","2016-03-01","2016-04-01","2016-05-01","2016-06-01","2016-07-01","2016-08-01","2016-09-01","2016-10-01","2016-11-01","2016-12-01","2017-01-01","2017-02-01","2017-03-01","2017-04-01","2017-05-01","2017-06-01","2017-07-01","2017-08-01","2017-09-01","2017-10-01","2017-11-01","2017-12-01","2018-01-01","2018-02-01","2018-03-01","2018-04-01","2018-05-01","2018-06-01","2018-07-01","2018-08-01","2018-09-01","2018-10-01","2018-11-01","2018-12-01","2019-01-01","2019-02-01","2019-03-01","2019-04-01","2019-05-01","2019-06-01","2019-07-01","2019-08-01","2019-09-01","2019-10-01","2019-11-01","2019-12-01","2020-01-01","2020-02-01","2020-03-01","2020-04-01","2020-05-01","2020-06-01","2020-07-01","2020-08-01","2020-09-01","2020-10-01","2020-11-01","2020-12-01","2021-01-01","2021-02-01","2021-03-01","2021-04-01","2021-05-01","2021-06-01","2021-07-01","2021-08-01","2021-09-01","2021-10-01","2021-11-01","2021-12-01","2022-01-01","2022-02-01","2022-03-01","2022-04-01","2022-05-01","2022-06-01","2022-07-01","2022-08-01","2022-09-01","2022-10-01","2022-11-01","2022-12-01","2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01"],"y":[18.125806451612902,18.046428571428571,8.2087096774193551,5.9406666666666661,332.57967741935477,299.98933333333326,75.561290322580646,48.819354838709678,1085.3533333333332,146.09999999999999,162.76666666666668,124.43870967741937,91.264516129032259,94.285714285714292,144.04838709677421,190.42666666666668,1425.322580645161,1916.5,260.60322580645163,177.53548387096777,87.963333333333338,121.2,146.97333333333333,114.79032258064517,114.29032258064517,104.625,144.97419354838709,265.67666666666662,1926.4516129032259,2304.9666666666662,315.25806451612908,144.06129032258065,60.771333333333331,39.670967741935485,53.990000000000002,94.41935483870968,76.522580645161284,101.97586206896553,96.774193548387103,489.26666666666671,1619.8064516129032,1249.9000000000003,153.68709677419355,133.68064516129033,73.074333333333328,44.073870967741939,13.68,11.942258064516128,72.432258064516134,67.517857142857139,27.807741935483872,21.762666666666664,902.14193548387107,1109.0999999999999,156.19032258064516,282.45161290322579,240.07333333333335,117.02580645161291,61.856666666666669,79.5741935483871,57.819354838709678,22.503214285714286,33.960645161290323,23.817666666666668,778.12903225806463,388.25333333333333,125.21612903225807,84.035483870967738,46.863333333333337,130.30000000000001,15.267999999999999,10.212903225806452,12.558709677419355,29.060714285714287,43.183870967741932,41.073333333333331,236.53548387096777,743.5333333333333,339.67741935483878,151.63870967741937,59.54666666666666,82.338709677419345,7.5010000000000003,39.806129032258063,25.961290322580645,16.967586206896552,12.301612903225807,25.099,234.41580645161287,433.41000000000008,101.01290322580645,66.406451612903226,31.838666666666668,93.033225806451625,9.6799999999999997,31.087096774193551,22.323870967741936,31.449999999999999,22.644193548387097,27.753333333333334,1227.8709677419354,657.83333333333337,111.7741935483871,76.213548387096779,11.582666666666666,25.545161290322582,37.219999999999999,40.848387096774196,57.806451612903224,55.36785714285714,14.366129032258065,35.910333333333327,262.72161290322578,510.75999999999993,102.59354838709677,59.882580645161298,18.518333333333334,69.109354838709663,11.209999999999999,10.371612903225806,7.2919354838709678,21.900357142857143,28.806451612903224,76.760000000000005,648.5,1499.2333333333333,187.67451612903224,91.032258064516128,37.510333333333328,73.877741935483868,17.914999999999999,13.609677419354838],"mode":"lines","line":{"color":"steelblue"},"type":"scatter","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="seasonal-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="seasonal-diagnostics">3. Seasonal Diagnostics</h2>
<p>Before fitting any model, inspect the seasonal structure using two complementary <code>feasts</code> plots.</p>
<p><strong>Subseries plot</strong> — one panel per month, each line is one year, the blue line is the monthly mean across all years:</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `gg_subseries()` was deprecated in feasts 0.4.2.
ℹ Please use `ggtime::gg_subseries()` instead.
ℹ Graphics functions have been moved to the {ggtime} package. Please use
  `library(ggtime)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-06_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Seasonal plot</strong> — each line is one year plotted over the calendar cycle. Parallel lines = stable seasonal shape; diverging lines = changing pattern:</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `gg_season()` was deprecated in feasts 0.4.2.
ℹ Please use `ggtime::gg_season()` instead.
ℹ Graphics functions have been moved to the {ggtime} package. Please use
  `library(ggtime)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-06_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Describe what you see. How are “seasons” defined in these plots? Is the seasonal shape consistent across years, or does it change? What physical process drives the May–June peak?</p>
<blockquote class="blockquote">
<p>May and June are the times of year with the highest peak flows. This is consistent across both plots that show the mean blue lines higher for monthly flow patterns for one plot, and the year lines peaking is the seasonal shape by year plot in May and June. Snowmelt is responsible for the peak seen during this time. 2013 is a bit of an outlier with a high peak occuring is September and lower peaks in May and June. This is not surprising though given the 2013 September flood was a major event the governor of Colorado declared a disaster emergency on September 12, 2013 accross 14 counties. Across years there are changes in how high the peak gets and the exact timing of the peak, but the overall shape is the same where snow begins melting in April, peaks sometime in May or June, and then goes back down by July.</p>
</blockquote>
</section>
<section id="stationarity-and-autocorrelation" class="level2">
<h2 class="anchored" data-anchor-id="stationarity-and-autocorrelation">4. Stationarity and Autocorrelation</h2>
<p>Two diagnostics that directly inform ARIMA model selection:</p>
<p><strong>Lag plot</strong> — plots Flow against its own lagged values. Strong linear patterns = high autocorrelation (ARIMA has something to work with). A diffuse cloud = no memory. Use <code>log1p(Flow)</code> — on the raw scale, peak months compress all other observations into the corner and hide the structure.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `gg_lag()` was deprecated in feasts 0.4.2.
ℹ Please use `ggtime::gg_lag()` instead.
ℹ Graphics functions have been moved to the {ggtime} package. Please use
  `library(ggtime)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-06_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Stationarity tests</strong> — ARIMA requires a stationary series (constant mean and variance). Test formally before fitting:</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in adf.test(log_flow_vec): p-value smaller than printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  log_flow_vec
Dickey-Fuller = -7.3292, Lag order = 5, p-value = 0.01
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Level Stationarity

data:  log_flow_vec
KPSS Level = 0.50753, Truncation lag parameter = 4, p-value = 0.03997</code></pre>
</div>
</div>
<p>What do the tests tell you? If the series is non-stationary, ARIMA will need <code>d ≥ 1</code> (differencing). Does the lag plot support the same conclusion?</p>
<blockquote class="blockquote">
<p>These tests use and alpha level of 0.05 to reject the null. The adf test gives a p-value of 0.01 meaning this test rejects non-stationarity concluding the test is stationary. The kpss test has a p-value of 0.0400 so the tests rejects stationarity concluding not stationary. These tests disagreeing suffests the series is a trend-stationary calling for detrending rather than differencing.</p>
</blockquote>
</section>
<section id="decomposition" class="level2">
<h2 class="anchored" data-anchor-id="decomposition">5. Decomposition</h2>
<p>Use <code>model(STL(...))</code> to decompose the time series into trend, seasonality, and remainder. Choose a trend window size you feel is appropriate and justify your choice. Extract components with <code>components()</code> and visualize with <code>autoplot()</code>.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `autoplot.dcmp_ts()` was deprecated in fabletools 0.6.0.
ℹ Please use `ggtime::autoplot.dcmp_ts()` instead.
ℹ Graphics functions have been moved to the {ggtime} package. Please use
  `library(ggtime)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-06_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Describe what you see:</p>
<ul>
<li>What does the <strong>trend</strong> tell you about long-term changes in Poudre flow? Is there evidence of a decline consistent with climate change or upstream demand?</li>
<li>What drives the <strong>seasonal</strong> component? (Hint: snowmelt, irrigation withdrawals, reservoir releases)</li>
<li>Are there any spikes in the <strong>remainder</strong> that correspond to anomalous years you can identify?</li>
</ul>
<blockquote class="blockquote">
<p>The trend was higher for a period of 2014-2016 and then it decreased. From 2018 onward the trend is oscilating around 100 where some periods it goes low when season goes high and then trend recovers to around 200. The lowest trend values are occuring in 2020-2023 suggesting evidence of decline. Seasonal component is regular fluculations. These are driven by snowmelt where season peaks when flow peaks. The season goes down following its peak where water is then being used for irrigation, and municipalities in the warmer months. A spike in the remainder occurs in 2013. This is likely due to the flood mentioned earlier that effected the Front range in September of 2013</p>
</blockquote>
<hr>
</section>
<section id="modeltime-prediction" class="level2">
<h2 class="anchored" data-anchor-id="modeltime-prediction">Modeltime Prediction</h2>
<section id="data-preparation" class="level3">
<h3 class="anchored" data-anchor-id="data-preparation">Data Preparation</h3>
<p>Convert the historic tsibble and future tibble to plain tibbles with a <code>Date</code> column for <code>modeltime</code>. All predictor columns must be present in both the historic and future datasets — this is what enables the 10-year climate-driven forecast.</p>
<p>Streamflow is strictly non-negative but right-skewed — snowmelt peaks dwarf base-flow months. To prevent models from predicting negative flows, add a <strong>log-transformed response</strong> with <code>log1p(Flow)</code> (<code>log(Flow + 1)</code>, safe when flow is near zero). Fit all models on <code>log_flow</code>; back-transform predictions with <code>expm1()</code> (= <code>exp(x) - 1</code>) to return to cfs units.</p>
</section>
<section id="train-test-split" class="level3">
<h3 class="anchored" data-anchor-id="train-test-split">Train / Test Split</h3>
<p>Hold out the last 24 months (2022–2023) as the test set. This mirrors the <code>assess = "60 months"</code> logic from the CO₂ and Lees Ferry examples — the test set is always the most recent data, never a random sample.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Using date_var: date</code></pre>
</div>
</div>
</section>
<section id="model-definition" class="level3">
<h3 class="anchored" data-anchor-id="model-definition">Model Definition</h3>
<p>Choose at least three models — one ARIMA and one Prophet are required. Store model specifications in a list:</p>
</section>
<section id="model-fitting" class="level3">
<h3 class="anchored" data-anchor-id="model-fitting">Model Fitting</h3>
<p>Fit all models to the training data on the log scale. Exclude the raw <code>Flow</code> column so models only see <code>log_flow</code> as the response — each engine handles <code>date</code> and climate predictors internally.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>frequency = 12 observations per 1 year
frequency = 12 observations per 1 year</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling weekly seasonality. Run prophet with weekly.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling weekly seasonality. Run prophet with weekly.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>frequency = 12 observations per 1 year</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'earth' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'plotmo' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'plotrix' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'plotrix'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:scales':

    rescale</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:terra':

    rescale</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Modeltime Table
# A tibble: 6 × 3
  .model_id .model   .model_desc                                   
      &lt;int&gt; &lt;list&gt;   &lt;chr&gt;                                         
1         1 &lt;fit[+]&gt; REGRESSION WITH ARIMA(3,1,0)(2,0,0)[12] ERRORS
2         2 &lt;fit[+]&gt; ARIMA(1,0,1)(0,1,1)[12] W/ XGBOOST ERRORS     
3         3 &lt;fit[+]&gt; PROPHET W/ REGRESSORS                         
4         4 &lt;fit[+]&gt; PROPHET W/ XGBOOST ERRORS                     
5         5 &lt;fit[+]&gt; ETS(A,N,A)                                    
6         6 &lt;fit[+]&gt; EARTH                                         </code></pre>
</div>
</div>
</section>
<section id="calibration-and-accuracy" class="level3">
<h3 class="anchored" data-anchor-id="calibration-and-accuracy">Calibration and Accuracy</h3>
<p>Calibrate on the test set (2022–2023) to compute out-of-sample accuracy metrics. Pass <code>select(testing, -Flow)</code> so calibration uses the log-scale response:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  .model_desc                                      mae  mape  mase  rmse   rsq
  &lt;chr&gt;                                          &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 EARTH                                          0.448  13.3 0.454 0.534 0.849
2 ETS(A,N,A)                                     0.511  15.7 0.518 0.621 0.820
3 ARIMA(1,0,1)(0,1,1)[12] W/ XGBOOST ERRORS      0.562  17.7 0.569 0.720 0.730
4 PROPHET W/ REGRESSORS                          0.580  16.0 0.588 0.692 0.783
5 REGRESSION WITH ARIMA(3,1,0)(2,0,0)[12] ERRORS 0.581  15.4 0.589 0.684 0.773
6 PROPHET W/ XGBOOST ERRORS                      0.683  18.0 0.692 0.753 0.790</code></pre>
</div>
</div>
<p>Describe what you see. Use these benchmarks to interpret the numbers:</p>
<ul>
<li><strong>MASE &lt; 1</strong> — the model beats a naïve seasonal forecast (last year’s same month)</li>
<li><strong>MAPE</strong> — intuitive % error, but inflated in low-flow months when Flow ≈ 0</li>
<li><strong>RMSE</strong> — penalizes large errors heavily; compare to mean test-period flow for context</li>
<li>Do boosted models (ARIMA-boost, Prophet-boost) outperform their base versions? If so, the nonlinear climate signal is worth capturing.</li>
</ul>
<blockquote class="blockquote">
<p>MASE was the smallest for MARS earth model (0.45). MAPE was highest for the XGBoost error models for both ARIMA and PROPHET (MAPE&gt;17.7). The lowest MAPE value belongs to the MARS (Earth) model MAPE=13.3. This represents the intuitive % error suggesting the MARS model outpreforms the others here. Root Mean Squar Error RMSE was largest for the XBOOST engines again (&gt;0.7), while the MARS model was the lowest again (RMSE= 0.53). The lowest model preformed the best because RMSE measures the magnitude of error (difference between predicted and actual). The best RSQ was also for MARS (0.85) suggesting this model explains the data best. Boosted methods are not clearly out preforming their base models. While Phrophet boost model has a better rsq (0.79 vs 0.78) it loses in terms of errors (RMSE 0.75 vs 0.69) and MAPE (17.95 vs 0.588).</p>
</blockquote>
</section>
<section id="test-set-forecast" class="level3">
<h3 class="anchored" data-anchor-id="test-set-forecast">Test Set Forecast</h3>
<p>Forecast over the held-out test period and compare predictions to actuals. Back-transform with <code>expm1()</code> to return predictions to cfs. Two details matter: (1) <code>expm1(x)</code> is the exact inverse of <code>log1p(x)</code> and always returns values ≥ 0; (2) confidence interval lower bounds on the log scale can be slightly negative — floor them at 0 with <code>pmax(.conf_lo, 0)</code> <em>before</em> back-transforming so the ribbon never dips below zero cfs:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-06_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Do predictions track actuals during the 2022–2023 test window? Are confidence intervals capturing observed values? Note any discontinuities at the 2022 boundary between training and test.</p>
<blockquote class="blockquote">
<p>The predictions do track actuals during this test window. The confidence intervals do capture the observed values. PHROPHET w/ regressors, PROPHET w/ XGBoost, and regression with ARIMA visually underpredicted for both 2022 and 2023. All models seemed to underpredict for 2023. MARS earth model was consistently the closest predictor line to observed values.</p>
</blockquote>
</section>
<section id="refit-to-full-dataset" class="level3">
<h3 class="anchored" data-anchor-id="refit-to-full-dataset">Refit to Full Dataset</h3>
<p>Refit all models to the complete 2013–2023 record before forecasting forward. Refitting allows auto-tuned models (<code>auto.arima</code>, <code>ets</code>) to re-optimize their parameters with more data:</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>frequency = 12 observations per 1 year
frequency = 12 observations per 1 year</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling weekly seasonality. Run prophet with weekly.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling weekly seasonality. Run prophet with weekly.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>frequency = 12 observations per 1 year</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  .model_desc                                        mae  mape  mase  rmse   rsq
  &lt;chr&gt;                                            &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 EARTH                                            0.448  13.3 0.454 0.534 0.849
2 ETS(A,N,A)                                       0.511  15.7 0.518 0.621 0.820
3 UPDATE: ARIMA(1,0,0)(0,1,1)[12] WITH DRIFT W/ X… 0.562  17.7 0.569 0.720 0.730
4 PROPHET W/ REGRESSORS                            0.580  16.0 0.588 0.692 0.783
5 REGRESSION WITH ARIMA(3,1,0)(2,0,0)[12] ERRORS   0.581  15.4 0.589 0.684 0.773
6 PROPHET W/ XGBOOST ERRORS                        0.683  18.0 0.692 0.753 0.790</code></pre>
</div>
</div>
<p>Do the accuracy metrics change after refitting? Why or why not? &gt; Accuracy metrics do not change after refitting because it is still using the same test data</p>
</section>
<section id="forecast-into-the-future-20242033" class="level3">
<h3 class="anchored" data-anchor-id="forecast-into-the-future-20242033">Forecast into the Future (2024–2033)</h3>
<p>Use the refitted models with <code>future_tbl</code> as <code>new_data</code> to generate a 10-year climate-conditioned forecast. Back-transform with <code>expm1()</code>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-06_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Negative?</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>future_forecast <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n_negative =</span> <span class="fu">sum</span>(.value <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  n_negative
       &lt;int&gt;
1          0</code></pre>
</div>
</div>
<hr>
</section>
</section>
<section id="wrap-up" class="level2">
<h2 class="anchored" data-anchor-id="wrap-up">Wrap-up</h2>
<p>Examine your 10-year forecast and reflect on the following:</p>
<ol type="1">
<li><strong>Model agreement</strong>: Do ARIMA and Prophet project similar trajectories? If they diverge, what does that tell you about their different assumptions (statistical stationarity vs.&nbsp;flexible trend)?</li>
</ol>
<blockquote class="blockquote">
<p>These models do not have the same trajectories. There are a few projected years, 2024, 2026, and 2032 where phrophet with regressors is predicting the highest peak streamflow out of all models wile ARIMA remains more conservative. The ARIMA models, specifically XGBoost, remains relatively consistent across all predicted years. ARIMA regression moves a little higher for flow prediction, but it is still smaller than the peaks of Prophet with regressors. Prophet XGBoost has an interesting pattern where it has small peaks following the peaks that the other models predicted, other than this difference this model is conservative in its predictions. ARIMA rely on assumptions of stationarity so it makes sense that these models produce smoother, more conservative forecasts. This compares to Prophet which can handle trend breaks, missing data, and multiple seasonalities. Allowing for more flexibility allows those larger peaks.</p>
</blockquote>
<ol start="2" type="1">
<li><strong>Forecast quality</strong>: Which model would you recommend to CWCB for water-supply planning? Justify with your accuracy metrics.</li>
</ol>
<blockquote class="blockquote">
<p>I would reccomend the MARS Earth model. This is because its accuracy metrics were the best. MASE was the smallest out of the models (0.45), the lowest MAPE (13.3), the lowest RMSE (0.53) and the rsq was the highest (0.85). This implies that this model fits the data best, while also not inflating error terms. The visual plot also showed the MARS model most closely aligning to observed data 2022-2023 period.</p>
</blockquote>
<ol start="3" type="1">
<li><strong>Negative predictions</strong>: If any model predicts negative flow, explain why this happens and what you would do to fix it in a production context (hint: log-transformation of Flow before modeling).</li>
</ol>
<blockquote class="blockquote">
<p>This model does not have any negative flow predicts. In this analysis, applying a log transformation to the response variable (log1p(flow)) before modeling and then back-transforming with expm1() helps avoid this issue by ensuring predictions remain positive.</p>
</blockquote>
<ol start="4" type="1">
<li><strong>Regressor value</strong>: The MACA climate projections assume a specific emissions scenario. How does uncertainty in those projections propagate into your streamflow forecast?</li>
</ol>
<blockquote class="blockquote">
<p>Uncertainty over the climate emission reality of the future introduces more uncertainty into these forecasting models. If emissions increase more than projected then climate effects like temperature, precipitation, and drought could be amplified in unaccounted for ways. This could result in the forecast under/over predicting. Many forecast models involving climate change include different emissions scenarios (RCP 8.5, RCP 6, RCP 2.6) so it may be wise to apply this methodology here too.</p>
</blockquote>
<ol start="5" type="1">
<li><strong>Improvement path</strong>: What information not in <code>tmax</code>, <code>ppt</code>, <code>srad</code> would most improve this forecast? (Consider: snowpack, upstream storage, irrigation demand.)</li>
</ol>
<blockquote class="blockquote">
<p>SWE could possibly help improve this forecast as the Poudre is a snowmelt driven system. Having data on storage release from resevoirs upstream could help explain patterns (or lack of) in flow. This could be especially important if NISP is ever completed, which would divert water from the Poudre, but also aledgedly suppplement flow in drier times. This could effect what the hydrograph of the Poudre looks like in areas affected by the reservoir.</p>
</blockquote>
<p>At this stage you have a working end-to-end time series forecasting pipeline — the same structural approach used by CWCB, USBR, and state water agencies for operational planning. The processes you learned in <code>tidymodels</code> apply directly here, and you can extend this framework with cross-validation (<code>time_series_cv()</code>), feature engineering (lag variables, rolling means), and hyperparameter tuning.</p>
<hr>
</section>
<section id="going-further-optional-add-an-upstream-regressor" class="level2">
<h2 class="anchored" data-anchor-id="going-further-optional-add-an-upstream-regressor">Going Further (Optional): Add an Upstream Regressor</h2>
<p>In lecture we showed that adding Glenwood Springs flow as an exogenous regressor improved Lees Ferry forecasts because upstream conditions carry physical information the model can’t infer from time structure alone. Try the same approach here.</p>
<p>Download data from a headwater gage on the Poudre (e.g., North Fork Cache la Poudre, USGS 06746095) and add it as a predictor:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>upstream <span class="ot">&lt;-</span> <span class="fu">readNWISdv</span>(</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">siteNumber  =</span> <span class="st">"06746095"</span>,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">parameterCd =</span> <span class="st">"00060"</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">startDate   =</span> <span class="st">"2013-01-01"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">endDate     =</span> <span class="st">"2023-12-31"</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">renameNWISColumns</span>() <span class="sc">|&gt;</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># floor_date returns the 1st of each month as a Date — same type as pf_tbl$date</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">floor_date</span>(Date, <span class="st">"month"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(date) <span class="sc">|&gt;</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">upstream_flow =</span> <span class="fu">mean</span>(Flow, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in readNWISdv(siteNumber = "06746095", parameterCd = "00060", startDate
= "2013-01-01", : NWIS servers are slated for decommission. Please begin to
migrate to read_waterdata_daily.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>GET: https://waterservices.usgs.gov/nwis/dv/?site=06746095&amp;format=waterml%2C1.1&amp;ParameterCd=00060&amp;StatCd=00003&amp;startDT=2013-01-01&amp;endDT=2023-12-31</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>pf_reg <span class="ot">&lt;-</span> pf_tbl <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(upstream, <span class="at">by =</span> <span class="st">"date"</span>) <span class="sc">|&gt;</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(upstream_flow)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>splits_reg <span class="ot">&lt;-</span> <span class="fu">time_series_split</span>(pf_reg, <span class="at">assess =</span> <span class="st">"24 months"</span>, <span class="at">cumulative =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Using date_var: date</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use log_flow ~ . consistent with the main pipeline; exclude raw Flow</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>models_reg <span class="ot">&lt;-</span> <span class="fu">map</span>(mods, <span class="sc">~</span> <span class="fu">fit</span>(.x, log_flow <span class="sc">~</span> .,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">data =</span> <span class="fu">select</span>(<span class="fu">training</span>(splits_reg), <span class="sc">-</span>Flow)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>frequency = 12 observations per 1 year</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>frequency = 12 observations per 1 year</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling weekly seasonality. Run prophet with weekly.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling weekly seasonality. Run prophet with weekly.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>frequency = 12 observations per 1 year</code></pre>
</div>
</div>
<p>Does adding upstream flow improve MASE on the test set? If yes, the physical signal is worth including. If not, the climate data alone may be sufficient for monthly aggregation at this timescale.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/maisiemoline\.github\.io\/2026-ESS-523c");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>